name: Publish Docs
on:
  push:
    tags: ['realm-react-v[0-9]+.[0-9]+.[0-9]+*', 'realm-web-v[0-9]+.[0-9]+.[0-9]+*', 'v[0-9]+.[0-9]+.[0-9]+*']
jobs:
  publish:
    name: echo
    runs-on: ubuntu-latest
    steps: echo "Hello"
