name: Publish Docs
on:
  release:
    types:
      - published
      - edited
  push:
    tags: ['realm-react-v[0-9]+.[0-9]+.[0-9]+*', 'realm-web-v[0-9]+.[0-9]+.[0-9]+*', 'v[0-9]+.[0-9]+.[0-9]+*']
jobs:
  publish:
    name: Build & Publish Realm Docs
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo ${{ github.ref_name }}
